# Generated by Django 2.0.2 on 2018-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200)),
                ('linetype', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Sentences',
            },
        ),
    ]
