# Generated by Django 2.0.2 on 2018-02-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanskritannotator', '0002_linetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('color_class', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('chunk_no', models.IntegerField(default=0)),
                ('lemma', models.CharField(max_length=100)),
                ('pre_verb', models.CharField(max_length=100)),
                ('morph', models.CharField(max_length=100)),
                ('colspan', models.IntegerField(default=0)),
                ('wordlength', models.IntegerField(default=0)),
                ('aux_info', models.CharField(max_length=100)),
                ('isEliminated', models.BooleanField(default=False)),
                ('isSelected', models.BooleanField(default=False)),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanskritannotator.Sentences')),
            ],
            options={
                'db_table': 'WordOptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wordoptions',
            unique_together={('sentence', 'level', 'color_class', 'position', 'chunk_no', 'lemma', 'pre_verb', 'morph', 'colspan', 'wordlength', 'aux_info')},
        ),
    ]
