# Generated by Django 2.0.2 on 2018-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskritannotator', '0003_auto_20180226_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoptions',
            name='word',
            field=models.CharField(default='', max_length=100),
        ),
    ]
