# Generated by Django 2.0.2 on 2018-04-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanskritannotator', '0004_wordoptions_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordsinsentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('parent', models.IntegerField(default=0)),
                ('children', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('wordoptions', models.CharField(max_length=100)),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanskritannotator.Sentences')),
            ],
            options={
                'db_table': 'Wordsinsentence',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wordsinsentence',
            unique_together={('sentence', 'word', 'parent', 'children', 'relation', 'wordoptions')},
        ),
    ]
